FROM postgres:13-alpine


LABEL mainteiner="tgorn@tgorn.eu"

COPY ./postgres /postgres
COPY ./postgres/pg_hba.conf /var/lib/postgresql/data/pg_hba.conf

WORKDIR /postgres

EXPOSE 5432

RUN cp /postgres/pg_hba.conf /var/lib/postgresql/data/pg_hba.conf 